<?php
require_once __DIR__.'/../config/db.php';require_once __DIR__.'/../includes/functions.php';requireAdmin();
$section=$_GET['section']??'overview';$adminId=(int)$_SESSION['admin_id'];$adminName=$_SESSION['admin_name']??'Admin';
if(isPost()){
 $action=$_POST['action']??'';$id=(int)($_POST['id']??0);
 try{
  if($action==='add_staff'){
    $name=trim($_POST['name']??'');$email=trim($_POST['email']??'');$staffNo=trim($_POST['staff_no']??'');$pass=$_POST['password']??'';
    if(!$name||!$email||!$staffNo||!$pass)throw new Exception('Name, email, staff number and password are required.');
    $u=$pdo->prepare("SELECT id FROM users WHERE email=? OR staff_no=? LIMIT 1");$u->execute([$email,$staffNo]);if($u->fetch())throw new Exception('Email or Staff Number already exists. Staff numbers must be unique.');
    $s=$pdo->prepare("INSERT INTO users(name,email,reg_no,staff_no,phone,gender,physical_address,id_passport_no,role,password,can_report_items,can_issue_items) VALUES(:n,:e,NULL,:staff,:phone,:gender,:address,:idno,'staff',:p,1,:issue)");
    $s->execute(['n'=>$name,'e'=>$email,'staff'=>$staffNo,'phone'=>trim($_POST['phone']??''),'gender'=>trim($_POST['gender']??''),'address'=>trim($_POST['physical_address']??''),'idno'=>trim($_POST['id_passport_no']??'')?:null,'p'=>password_hash($pass,PASSWORD_DEFAULT),'issue'=>isset($_POST['can_issue_items'])?1:0]);
    logActivity($pdo,'admin',$adminId,$adminName,'Added staff',$name.' ('.$staffNo.')');flash('success','Staff account created. Reporting items is enabled by default.');
  }elseif($action==='edit_staff'){
    $name=trim($_POST['name']??'');$email=trim($_POST['email']??'');$staffNo=trim($_POST['staff_no']??'');if(!$name||!$email||!$staffNo)throw new Exception('Name, email and staff number are required.');
    $u=$pdo->prepare("SELECT id FROM users WHERE (email=? OR staff_no=?) AND id<>? LIMIT 1");$u->execute([$email,$staffNo,$id]);if($u->fetch())throw new Exception('Email or Staff Number is already used by another account.');
    $sql="UPDATE users SET name=:n,email=:e,staff_no=:staff,phone=:phone,gender=:gender,physical_address=:address,id_passport_no=:idno,can_report_items=1,can_issue_items=:issue";$params=['n'=>$name,'e'=>$email,'staff'=>$staffNo,'phone'=>trim($_POST['phone']??''),'gender'=>trim($_POST['gender']??''),'address'=>trim($_POST['physical_address']??''),'idno'=>trim($_POST['id_passport_no']??'')?:null,'issue'=>isset($_POST['can_issue_items'])?1:0,'id'=>$id];
    if(($_POST['password']??'')!==''){$sql.=',password=:password';$params['password']=password_hash($_POST['password'],PASSWORD_DEFAULT);} $sql.=" WHERE id=:id AND role='staff'";$pdo->prepare($sql)->execute($params);logActivity($pdo,'admin',$adminId,$adminName,'Edited staff',$name.' ('.$staffNo.')');flash('success','Staff details updated.');
  }elseif($action==='delete_staff'){$ds=$pdo->prepare("SELECT name,staff_no FROM users WHERE id=? AND role='staff'");$ds->execute([$id]);$deleted=$ds->fetch();$pdo->prepare("DELETE FROM users WHERE id=? AND role='staff'")->execute([$id]);if($deleted)logActivity($pdo,'admin',$adminId,$adminName,'Removed Staff',($deleted['name']??'Staff').' ('.($deleted['staff_no']??'').')','staff',$id);flash('success','Staff account removed.');
  }elseif(in_array($action,['approve_item','reject_item'],true)){
    // Pending items only come from ordinary users reporting found property.
    $status=$action==='approve_item'?'approved':'rejected';$uq=$pdo->prepare("UPDATE items SET status=?,reviewed_by_admin_id=? WHERE id=? AND status='pending'");$uq->execute([$status,$adminId,$id]);if($uq->rowCount())logActivity($pdo,'admin',$adminId,$adminName,ucfirst($status).' User Found Report','Item #'.$id,'item',$id);flash('success','Found-item report updated.');
  }elseif($action==='issue_item'){
    $c=$pdo->prepare("SELECT c.*,i.title FROM claims c JOIN items i ON i.id=c.item_id WHERE c.id=? AND c.status='approved'");$c->execute([$id]);$claim=$c->fetch();if(!$claim)throw new Exception('Approved claim not found.');
    $pdo->beginTransaction();$pdo->prepare("INSERT INTO issued_items(item_id,claim_id,issued_to_user_id,issued_to_name,issued_by_admin_id,issued_by_name,issuer_role,verification_notes) VALUES(?,?,NULL,?,?,?,'admin',?)")->execute([$claim['item_id'],$id,$claim['claimant_name'],$adminId,$adminName,trim($_POST['verification_notes']??'')]);$pdo->prepare("UPDATE claims SET status='issued',issued_at=NOW() WHERE id=?")->execute([$id]);$pdo->prepare("UPDATE items SET status='issued' WHERE id=?")->execute([$claim['item_id']]);$pdo->commit();logActivity($pdo,'admin',$adminId,$adminName,'Issued Item',$claim['title'].' to '.$claim['claimant_name'],'item',(int)$claim['item_id']);flash('success','Item issued and recorded.');
  }
 }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();flash('error',$e->getMessage());}
 redirect(appUrl('admin/dashboard.php?section='.$section));
}
$stats=['users'=>$pdo->query("SELECT COUNT(*) FROM users WHERE role IN ('student','visitor')")->fetchColumn(),'staff'=>$pdo->query("SELECT COUNT(*) FROM users WHERE role='staff'")->fetchColumn(),'pending'=>$pdo->query("SELECT COUNT(*) FROM items WHERE status='pending'")->fetchColumn(),'claims'=>$pdo->query("SELECT COUNT(*) FROM claims WHERE status='approved'")->fetchColumn()];
$filterType=trim($_GET['type']??'');$filterClaim=trim($_GET['claim']??'');$filterCategory=trim($_GET['category']??'');
$itemSql="SELECT * FROM items WHERE 1=1";$itemParams=[];
if(in_array($filterType,['lost','found'],true)){$itemSql.=" AND item_type=:ftype";$itemParams['ftype']=$filterType;}
if($filterClaim==='claimed'){$itemSql.=" AND status IN ('claimed','issued')";}elseif($filterClaim==='not_claimed'){$itemSql.=" AND status='approved'";}
if($filterCategory!==''){$itemSql.=" AND category=:fcategory";$itemParams['fcategory']=$filterCategory;}
$itemSql.=" ORDER BY id DESC";$itemStmt=$pdo->prepare($itemSql);$itemStmt->execute($itemParams);$items=$itemStmt->fetchAll();
$claims=$pdo->query("SELECT c.*,i.title,i.item_type,i.category,i.reporter_name,i.reporter_phone,i.user_id AS item_reporter_user_id FROM claims c JOIN items i ON i.id=c.item_id ORDER BY c.id DESC")->fetchAll();$staff=$pdo->query("SELECT * FROM users WHERE role='staff' ORDER BY id DESC")->fetchAll();$users=$pdo->query("SELECT * FROM users WHERE role IN ('student','visitor') ORDER BY id DESC")->fetchAll();$issued=$pdo->query("SELECT x.*,i.title FROM issued_items x JOIN items i ON i.id=x.item_id ORDER BY x.id DESC")->fetchAll();$activity=$pdo->query("SELECT * FROM activity_logs ORDER BY id DESC LIMIT 100")->fetchAll();
$editStaff=null;if($section==='staff'&&!empty($_GET['edit'])){$es=$pdo->prepare("SELECT * FROM users WHERE id=? AND role='staff'");$es->execute([(int)$_GET['edit']]);$editStaff=$es->fetch();}
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Admin Dashboard</title><link rel="stylesheet" href="<?php echo appUrl('assets/css/style.css');?>"></head><body class="portal-body"><div class="portal-layout"><aside class="sidebar"><a class="sidebar-brand" href="?section=overview"><span class="brand-mark">C</span><span><strong>CUEA</strong><small>Admin Console</small></span></a><nav><a class="<?php echo $section==='overview'?'active':'';?>" href="?section=overview">Dashboard</a><a class="<?php echo $section==='items'?'active':'';?>" href="?section=items">Lost &amp; Found Items</a><a href="<?php echo appUrl('report-item.php?type=lost');?>">Report Lost Item</a><a href="<?php echo appUrl('report-item.php?type=found');?>">Report Found Item</a><a class="<?php echo $section==='claims'?'active':'';?>" href="?section=claims">Claim Requests</a><a class="<?php echo in_array($section,['issue','issued'],true)?'active':'';?>" href="?section=issue">Issue &amp; Issued Items</a><a class="<?php echo $section==='staff'?'active':'';?>" href="?section=staff">Staff Management</a><a class="<?php echo $section==='users'?'active':'';?>" href="?section=users">Users</a><a class="<?php echo $section==='activity'?'active':'';?>" href="?section=activity">Activity Log</a><a href="<?php echo appUrl('index.php');?>">Public Landing Page</a><a href="logout.php">Logout</a></nav></aside><main class="portal-main"><div class="portal-top"><div><p class="eyebrow">ADMINISTRATION</p><h1><?php echo e($adminName);?></h1></div></div><?php if($m=flash('success')):?><div class="alert success"><?php echo e($m);?></div><?php endif;?><?php if($m=flash('error')):?><div class="alert error"><?php echo e($m);?></div><?php endif;?>
<?php if($section==='overview'):?><div class="stats"><div class="card kpi"><strong><?php echo $stats['users'];?></strong><span>Users</span></div><div class="card kpi"><strong><?php echo $stats['staff'];?></strong><span>Staff</span></div><div class="card kpi"><strong><?php echo $stats['pending'];?></strong><span>User Found Reports Pending</span></div><div class="card kpi"><strong><?php echo $stats['claims'];?></strong><span>Claims Ready to Issue</span></div></div><div class="quick-actions"><a class="quick-card" href="<?php echo appUrl('report-item.php?type=lost');?>"><strong>Report Lost Item</strong><span>Publishes immediately</span></a><a class="quick-card" href="?section=claims"><strong>Claims</strong><span>Review onsite claimant records</span></a><a class="quick-card" href="?section=staff"><strong>Staff</strong><span>Edit details and issuing permission</span></a><a class="quick-card" href="<?php echo appUrl('items.php');?>"><strong>Public Items</strong><span>Open filtered item listing</span></a></div><?php endif;?>
<?php if($section==='items'):?><div class="card table-wrap"><h2>All Item Reports</h2><form class="filters" method="GET"><input type="hidden" name="section" value="items"><select name="type"><option value="">Lost & Found</option><option value="lost" <?php echo $filterType==='lost'?'selected':'';?>>Lost</option><option value="found" <?php echo $filterType==='found'?'selected':'';?>>Found</option></select><select name="claim"><option value="">Claimed & Not Claimed</option><option value="claimed" <?php echo $filterClaim==='claimed'?'selected':'';?>>Claimed</option><option value="not_claimed" <?php echo $filterClaim==='not_claimed'?'selected':'';?>>Not Claimed</option></select><select name="category"><option value="">All categories</option><?php foreach(itemCategories() as $cat):?><option value="<?php echo e($cat);?>" <?php echo $filterCategory===$cat?'selected':'';?>><?php echo e($cat);?></option><?php endforeach;?></select><button class="btn btn-sm">Filter</button><a class="btn outline btn-sm" href="?section=items">Clear</a></form><table><thead><tr><th>Item</th><th>Type</th><th>Reporter</th><th>Status</th><th>Actions</th></tr></thead><tbody><?php foreach($items as $i):?><tr><td><strong><?php echo e($i['title']);?></strong><br><span class="small"><?php echo e($i['category'].' · '.$i['location']);?></span></td><td><?php echo e(itemTypeLabel($i['item_type']));?></td><td><?php echo e($i['reporter_name']);?></td><td><span class="<?php echo badgeClass($i['status']);?>"><?php echo e(statusLabel($i['status']));?></span></td><td><a class="btn outline btn-sm" href="<?php echo appUrl('item.php?id='.$i['id']);?>">More Details</a><?php if($i['status']==='approved'):?> <a class="btn btn-sm" href="<?php echo appUrl('claim-intake.php?item_id='.$i['id']);?>">Capture Claim</a><?php endif;?><?php if($i['status']==='pending'):?><form method="POST" class="inline-form" style="margin-top:6px"><input type="hidden" name="id" value="<?php echo $i['id'];?>"><button class="btn success btn-sm" name="action" value="approve_item">Approve User Found Report</button><button class="btn danger btn-sm" name="action" value="reject_item">Reject</button></form><?php endif;?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?>
<?php if($section==='claims'):?><div class="card table-wrap"><h2>Onsite Claim Records</h2><div class="alert error"><strong>Verification rule:</strong> Claimants must present a valid ID/Passport and valid Police Abstract onsite. A verified claim is approved automatically when captured; there is no separate approve/reject step.</div><table><thead><tr><th>Item</th><th>Claimant</th><th>Documents</th><th>Status</th><th>Action</th></tr></thead><tbody><?php foreach($claims as $c):?><tr><td><strong><?php echo e($c['title']);?></strong><br><a class="small" href="<?php echo appUrl('item.php?id='.$c['item_id']);?>">More Details</a></td><td><?php echo e($c['claimant_name']);?><br><span class="small"><?php echo e($c['claimant_type']??'');?> · <?php echo e($c['claimant_phone']);?></span><br><span class="small">ID/Passport: <?php echo e($c['id_passport_no']??'—');?><?php if(!empty($c['registration_no'])):?> · Reg: <?php echo e($c['registration_no']);?><?php endif;?><?php if(!empty($c['staff_no'])):?> · Staff: <?php echo e($c['staff_no']);?><?php endif;?></span></td><td><?php if(!empty($c['police_abstract_file'])):?><a class="btn outline btn-sm" target="_blank" href="<?php echo appUrl('uploads/'.$c['police_abstract_file']);?>">Police Abstract</a><?php else:?>Missing<?php endif;?></td><td><span class="<?php echo badgeClass($c['status']);?>"><?php echo e(statusLabel($c['status']));?></span></td><td><span class="small">Automatic after onsite capture</span></td></tr><?php endforeach;?></tbody></table></div><?php endif;?>
<?php if(in_array($section,['issue','issued'],true)):?><div class="card table-wrap"><h2>Pending Issues</h2><p class="small">Verified claims that are ready for item handover.</p><table><thead><tr><th>Item</th><th>Claimant</th><th>Issue</th></tr></thead><tbody><?php $pendingIssueCount=0; foreach($claims as $c):if($c['status']!=='approved')continue;$pendingIssueCount++;?><tr><td><?php echo e($c['title']);?> <a class="small" href="<?php echo appUrl('item.php?id='.$c['item_id']);?>">More Details</a></td><td><?php echo e($c['claimant_name']);?><br><span class="small"><?php echo e($c['claimant_phone']);?></span></td><td><form method="POST"><input type="hidden" name="id" value="<?php echo $c['id'];?>"><input name="verification_notes" placeholder="Final onsite verification notes" required><button class="btn" name="action" value="issue_item">Issue Item</button></form></td></tr><?php endforeach;?><?php if(!$pendingIssueCount):?><tr><td colspan="3">No pending issues.</td></tr><?php endif;?></tbody></table></div><div class="card table-wrap section-gap"><h2>Issued Items</h2><p class="small">Completed item handovers.</p><table><thead><tr><th>Item</th><th>Issued to</th><th>Issued by</th><th>Notes</th><th>Date</th></tr></thead><tbody><?php foreach($issued as $x):?><tr><td><?php echo e($x['title']);?></td><td><?php echo e($x['issued_to_name']);?></td><td><?php echo e($x['issued_by_name']);?> (<?php echo e($x['issuer_role']);?>)</td><td><?php echo e($x['verification_notes']);?></td><td><?php echo e($x['issued_at']);?></td></tr><?php endforeach;?><?php if(!$issued):?><tr><td colspan="5">No issued items yet.</td></tr><?php endif;?></tbody></table></div><?php endif;?>
<?php if($section==='staff'):?><div class="grid-2"><div class="card"><h2><?php echo $editStaff?'Edit Staff':'Add Staff';?></h2><p class="small">Reporting items is enabled automatically for every staff account. Only issuing permission is configurable.</p><form method="POST"><input type="hidden" name="action" value="<?php echo $editStaff?'edit_staff':'add_staff';?>"><?php if($editStaff):?><input type="hidden" name="id" value="<?php echo $editStaff['id'];?>"><?php endif;?><label>Full name</label><input name="name" required value="<?php echo e($editStaff['name']??'');?>"><div class="form-grid"><div><label>Email</label><input type="email" name="email" required value="<?php echo e($editStaff['email']??'');?>"></div><div><label>Staff Number</label><input name="staff_no" required value="<?php echo e($editStaff['staff_no']??'');?>"><span class="small">Must be unique.</span></div></div><div class="form-grid"><div><label>Phone</label><input name="phone" value="<?php echo e($editStaff['phone']??'');?>"></div><div><label>Gender</label><select name="gender"><option value="">Select</option><?php foreach(['Female','Male','Other','Prefer not to say'] as $g):?><option <?php echo (($editStaff['gender']??'')===$g)?'selected':'';?>><?php echo e($g);?></option><?php endforeach;?></select></div></div><label>Physical address</label><textarea name="physical_address"><?php echo e($editStaff['physical_address']??'');?></textarea><label>ID / Passport</label><input name="id_passport_no" value="<?php echo e($editStaff['id_passport_no']??'');?>"><label><?php echo $editStaff?'New password (leave blank to keep current password)':'Password';?></label><input type="password" name="password" <?php echo $editStaff?'':'required';?>><label class="check-row"><input type="checkbox" name="can_issue_items" value="1" <?php echo !empty($editStaff['can_issue_items'])?'checked':'';?>> Can Issue Item</label><button class="btn"><?php echo $editStaff?'Save Staff Changes':'Create Staff';?></button><?php if($editStaff):?> <a class="btn outline" href="?section=staff">Cancel</a><?php endif;?></form></div><div class="card table-wrap"><h2>Existing Staff</h2><table><thead><tr><th>Staff</th><th>Access</th><th>Actions</th></tr></thead><tbody><?php foreach($staff as $s):?><tr><td><strong><?php echo e($s['name']);?></strong><br><span class="small"><?php echo e($s['staff_no']?:'No staff number');?> · <?php echo e($s['email']);?></span></td><td>Report: Default<br>Issue: <?php echo $s['can_issue_items']?'Yes':'No';?></td><td><a class="btn outline btn-sm" href="?section=staff&edit=<?php echo $s['id'];?>">Edit</a><form method="POST" style="margin-top:6px"><input type="hidden" name="action" value="delete_staff"><input type="hidden" name="id" value="<?php echo $s['id'];?>"><button class="btn danger btn-sm">Remove</button></form></td></tr><?php endforeach;?></tbody></table></div></div><?php endif;?>
<?php if($section==='users'):?><div class="card table-wrap"><h2>Registered Users</h2><table><thead><tr><th>Name</th><th>Category</th><th>Registration No.</th><th>Phone</th><th>Email</th><th>Gender</th><th>Address</th><th>ID/Passport</th></tr></thead><tbody><?php foreach($users as $u):?><tr><td><?php echo e($u['name']);?></td><td><?php echo e(ucfirst($u['role']));?></td><td><?php echo e($u['reg_no']?:'—');?></td><td><?php echo e($u['phone']);?></td><td><?php echo e($u['email']);?></td><td><?php echo e($u['gender']);?></td><td><?php echo e($u['physical_address']);?></td><td><?php echo e($u['id_passport_no']?:'—');?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?>

<?php if($section==='activity'):?><div class="card table-wrap"><h2>Activity Log</h2><table><thead><tr><th>Actor</th><th>Action</th><th>Details</th><th>Date</th></tr></thead><tbody><?php foreach($activity as $a):?><tr><td><?php echo e($a['actor_name']??'System');?> <span class="small"><?php echo e($a['actor_role']??($a['actor_type']??''));?></span></td><td><?php echo e($a['action']);?></td><td><?php echo e($a['description']??($a['details']??''));?></td><td><?php echo e($a['created_at']);?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?>
</main></div></body></html>
