CREATE DATABASE IF NOT EXISTS cuea_lost_found CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE cuea_lost_found;
CREATE TABLE IF NOT EXISTS admins (id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100) NOT NULL,email VARCHAR(150) NOT NULL UNIQUE,password VARCHAR(255) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS users (id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(150) NOT NULL,email VARCHAR(150) NOT NULL UNIQUE,reg_no VARCHAR(100) NULL,staff_no VARCHAR(100) NULL UNIQUE,phone VARCHAR(50) NULL,gender VARCHAR(40) NULL,physical_address VARCHAR(255) NULL,id_passport_no VARCHAR(100) NULL,role ENUM('student','visitor','staff') NOT NULL DEFAULT 'student',password VARCHAR(255) NOT NULL,can_report_items TINYINT(1) NOT NULL DEFAULT 0,can_issue_items TINYINT(1) NOT NULL DEFAULT 0,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS items (id INT AUTO_INCREMENT PRIMARY KEY,user_id INT NULL,item_type ENUM('lost','found') NOT NULL,category VARCHAR(100) NOT NULL,title VARCHAR(150) NOT NULL,description TEXT NULL,location VARCHAR(150) NOT NULL,date_reported DATE NOT NULL,reporter_name VARCHAR(150) NOT NULL,reporter_email VARCHAR(150) NULL,reporter_phone VARCHAR(50) NULL,reporter_reg_no VARCHAR(100) NULL,reporter_staff_no VARCHAR(100) NULL,image VARCHAR(255) DEFAULT NULL,brand VARCHAR(100) NULL,model VARCHAR(120) NULL,color VARCHAR(80) NULL,serial_number VARCHAR(150) NULL,matched_lost_item_id INT NULL,status ENUM('pending','approved','claimed','issued','rejected') DEFAULT 'pending',reviewed_by_staff_id INT NULL,reviewed_by_admin_id INT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL,FOREIGN KEY(reviewed_by_staff_id) REFERENCES users(id) ON DELETE SET NULL,FOREIGN KEY(reviewed_by_admin_id) REFERENCES admins(id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS claims (id INT AUTO_INCREMENT PRIMARY KEY,item_id INT NOT NULL,user_id INT NULL,claimant_type ENUM('student','staff','other') NULL,claimant_name VARCHAR(150) NOT NULL,id_passport_no VARCHAR(100) NULL,registration_no VARCHAR(100) NULL,staff_no VARCHAR(100) NULL,claimant_email VARCHAR(150) NULL,claimant_phone VARCHAR(50) NOT NULL,physical_address VARCHAR(255) NULL,gender VARCHAR(40) NULL,police_abstract_file VARCHAR(255) NULL,message TEXT NULL,status ENUM('pending','approved','rejected','issued') DEFAULT 'pending',captured_by_type VARCHAR(30) NULL,captured_by_id INT NULL,captured_by_name VARCHAR(150) NULL,verified_onsite TINYINT(1) NOT NULL DEFAULT 0,reviewed_by_staff_id INT NULL,reviewed_by_admin_id INT NULL,reviewed_at DATETIME NULL,issued_at DATETIME NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(item_id) REFERENCES items(id) ON DELETE CASCADE,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL,FOREIGN KEY(reviewed_by_staff_id) REFERENCES users(id) ON DELETE SET NULL,FOREIGN KEY(reviewed_by_admin_id) REFERENCES admins(id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS issued_items (id INT AUTO_INCREMENT PRIMARY KEY,item_id INT NOT NULL,claim_id INT NOT NULL,issued_to_user_id INT NULL,issued_to_name VARCHAR(150) NOT NULL,issued_by_staff_id INT NULL,issued_by_admin_id INT NULL,issued_by_name VARCHAR(150) NOT NULL,issuer_role ENUM('staff','admin') NOT NULL,verification_notes TEXT NULL,issued_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_claim_issue(claim_id),FOREIGN KEY(item_id) REFERENCES items(id) ON DELETE CASCADE,FOREIGN KEY(claim_id) REFERENCES claims(id) ON DELETE CASCADE,FOREIGN KEY(issued_to_user_id) REFERENCES users(id) ON DELETE SET NULL,FOREIGN KEY(issued_by_staff_id) REFERENCES users(id) ON DELETE SET NULL,FOREIGN KEY(issued_by_admin_id) REFERENCES admins(id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS activity_logs (id INT AUTO_INCREMENT PRIMARY KEY,actor_type VARCHAR(30) NOT NULL,actor_id INT NULL,actor_name VARCHAR(150) NOT NULL,action VARCHAR(150) NOT NULL,details TEXT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS notifications_log (id INT AUTO_INCREMENT PRIMARY KEY,recipient_email VARCHAR(150) NOT NULL,subject_line VARCHAR(255) NOT NULL,message_body TEXT NOT NULL,sent_status ENUM('queued','sent') NOT NULL DEFAULT 'queued',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
INSERT INTO admins(name,email,password) VALUES('System Admin','admin@cuea.edu','$2y$12$LUrV325bFLH8Q3T/I8UtAO4DEff8fvstC5zZxOQrXXFgtaJIX2P1.') ON DUPLICATE KEY UPDATE email=email;
INSERT INTO users(name,email,reg_no,staff_no,phone,gender,physical_address,id_passport_no,role,password,can_report_items,can_issue_items) VALUES('Demo Student','student@cuea.edu',NULL,NULL,NULL,NULL,NULL,NULL,'student','$2y$12$FPKF6KJTVivUw0mBOgoEeOaACm1s.X46B2dvjrqkQLspvhcQLPkX.',0,0),('Demo Staff','staff@cuea.edu',NULL,'CUEA/SF/001',NULL,NULL,NULL,NULL,'staff','$2y$12$FPKF6KJTVivUw0mBOgoEeOaACm1s.X46B2dvjrqkQLspvhcQLPkX.',1,1) ON DUPLICATE KEY UPDATE email=email;
-- Admin: admin@cuea.edu / admin123
-- Student: student@cuea.edu / password123
-- Staff: staff@cuea.edu / password123
